// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyyWYADDhKl33t_3LzyCXg8hLIoEdXsyQ',
    appId: '1:946264290866:web:b8b1779ccd95539ca0ae2b',
    messagingSenderId: '946264290866',
    projectId: 'fore-m-1',
    authDomain: 'fore-m-1.firebaseapp.com',
    storageBucket: 'fore-m-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcuNJlwGySn51D28wPRfOiTztnBi-u2W0',
    appId: '1:946264290866:android:9bcf3197e93bd1cea0ae2b',
    messagingSenderId: '946264290866',
    projectId: 'fore-m-1',
    storageBucket: 'fore-m-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_JGjRUKMZbUbQO2RaJjpBfoRTqWyRQ7M',
    appId: '1:946264290866:ios:f092ffc9e0de92e4a0ae2b',
    messagingSenderId: '946264290866',
    projectId: 'fore-m-1',
    storageBucket: 'fore-m-1.appspot.com',
    iosClientId: '946264290866-hmqq1dbeoimiaa77ccosqm8nrum70nd0.apps.googleusercontent.com',
    iosBundleId: 'com.tes',
  );
}
